name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  call-deploy:
    uses: softscriptdev/actions/.github/workflows/deploy.yml@main
    with:
          base-path: "/sunnyside-agency-landing-page-main/"
